### ISSUE TITLE
Bug in reading uff 55 files

### ISSUE THREAD

**Issue by yjchan-mech-nchu** [sandialabs/sdynpy#13]
I have found some bugs in SDynPy on reading uff 55 files, especially on complex frequencies/mode shapes. The fixed version is attached: see lines 384, 408-412 and 432 in the attachment.
[sdynpy_uff_dataset_55.zip](https://github.com/sandialabs/sdynpy/files/14274996/sdynpy_uff_dataset_55.zip)

**Comment by dprohe** [comment]
Thanks for this report.  This should be fixed with the v0.14 update.  Let me know if you still have issues.
